# Generated by Django 4.1.2 on 2022-10-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_eancho_employee_lonas_employee_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='categoria',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eancho',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fabricante',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='indi_carga',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='indi_velocidad',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lonas',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='perfil',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rin',
            field=models.CharField(default='', max_length=15),
        ),
    ]
